export default `
March 4, 2013
Canon Inc.
Canon develops 35 mm full-frame CMOS sensor for video capture
TOKYO, March 4, 2013—Canon Inc. announced today that the company has successfully developed a high-sensitivity 35 mm full-frame CMOS sensor exclusively for video recording. Delivering high-sensitivity, low-noise imaging performance, the new Canon 35 mm CMOS sensor*1 enables the capture of Full HD video even in exceptionally low-light environments.
The newly developed CMOS sensor features pixels measuring 19 microns square in size, which is more than 7.5-times the surface area of the pixels on the CMOS sensor incorporated in Canon's top-of-the-line EOS-1D X and other digital SLR cameras. In addition, the sensor's pixels and readout circuitry employ new technologies that reduce noise, which tends to increase as pixel size increases. Thanks to these technologies, the sensor facilitates the shooting of clearly visible video images even in dimly lit environments with as little as 0.03 lux of illumination, or approximately the brightness of a crescent moon—a level of brightness in which it is difficult for the naked eye to perceive objects. When recording video of astral bodies, while an electron-multiplying CCD,*2 which realizes approximately the same level of perception as the naked eye, can capture magnitude-6 stars, Canon's newly developed CMOS sensor is capable of recording faint stars with a magnitude of 8.5 and above.*3
Using a prototype camera employing the newly developed sensor, Canon successfully captured a wide range of test video,*4 such as footage recorded in a room illuminated only by the light from burning incense sticks (approximately 0.05—0.01 lux) and video of the Geminid meteor shower. The company is looking to such future applications for the new sensor as astronomical and natural observation, support for medical research, and use in surveillance and security equipment. Through the further development of innovative CMOS sensors, Canon aims to expand the world of new imaging expression.
Canon Marketing Japan Inc. will be exhibiting a prototype camera that incorporates the newly developed 35 mm full-frame CMOS sensor and sample footage captured with the camera at SECURITY SHOW 2013 (www.shopbiz.jp/en/ss/), which will be held from Tuesday, March 5, to Friday, March 8, at the Tokyo International Exhibition Center in Tokyo, Japan.
*1An imaging element (aspect ratio: 16:9) that supports the largest image circle size possible when shooting with a Canon EF lens.
*2A CCD sensor with a readout mechanism that multiplies electrons after being converted from light. Applications include nighttime surveillance and the capture of astral bodies and nighttime nature scenes.
*3The brightness of a star decreases 2.5-times with each 1 magnitude increase.
*4Recording of test video footage was made possible through cooperation from ZERO Corporation.
`;
